apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
  labels:
    name: prometheus-server-conf
  namespace: monitoring-v2
data:
  prometheus.yml: |-
   scrape_configs:
   - job_name: 'prometheus'
     scrape_interval: 10s
     static_configs:
        - targets: ['localhost:9090']
      
   - job_name: 'zeeshanc'
     scrape_interval: 10s
     honor_labels: true
     static_configs:
       - targets: ['exporterapp:8000']