{
 "title": "Status server",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "200 response time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sample_external_url_response_ms{endpoint=\"https://httpstat.us/200\"}"
    }
   ]
  },
  {
   "title": "500 response time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sample_external_url_response_ms{endpoint=\"https://httpstat.us/503\"}"
    }
   ]
  },
  {
   "title": "Response time https://httpstat.us/503",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sample_external_url_response_ms{endpoint=\"https://httpstat.us/503\"}"
    }
   ]
  },
  {
   "title": "Response time https://httpstat.us/200",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sample_external_url_response_ms{endpoint=\"https://httpstat.us/200\"}"
    }
   ]
  },
  {
   "title": "Status history",
   "type": "status-history",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 17 },
   "targets": [
    { "expr": "sample_external_url_up" }
   ]
  }
 ]
}