{
 "title": "Status serverx",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Site Status",
   "type": "status-history",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "sample_external_url_up", "legendFormat": "{{endpoint}}" }
   ]
  },
  {
   "title": "Response time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(sample_external_url_response_ms{endpoint=\"https://httpstat.us/200\"}[1m])*1000",
     "legendFormat": "{{endpoint}}"
    },
    {
     "expr": "rate(sample_external_url_response_ms{endpoint=\"https://httpstat.us/503\"}[1m])*1000",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Response time https://httpstat.us/200",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(sample_external_url_response_ms{endpoint=\"https://httpstat.us/200\"}[1m])*1000"
    }
   ]
  },
  {
   "title": "Response time https://httpstat.us/503",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(sample_external_url_response_ms{endpoint=\"https://httpstat.us/503\"}[1m])* 1000"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } }
 ]
}