apiVersion: v1
kind: Namespace
metadata:
  name: monitoring-v2

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: exporterapp
  namespace: monitoring-v2
  labels:
    app: exporterapp
spec:
  selector:
    matchLabels:
      app: exporterapp
  replicas: 1
  template:
    metadata:
      labels:
        app: exporterapp
    spec:
      containers:
      - name: exporterapp
        image: zeeshanshahid/exporterapp:1.1
        imagePullPolicy: Never
        ports:
        - name: exporterapp
          containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: exporterapp
  namespace: monitoring-v2
  labels:
    app: exporterapp
spec:
  type: NodePort
  selector:
    app: exporterapp
  ports:
  - name: exporterapp
    port: 8000
    targetPort: 8000

